spring:
  main:
    banner-mode: OFF

server:
  port: 7075
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true

# Local environment settings. Will be overridden in dev and prod.

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_GROUP_ID: klage-arkiver-journalpost
KAFKA_TOPIC: aapen-klager-klageOpprettet

SERVICE_USER_USERNAME: srvklage-dittnav
SERVICE_USER_PASSWORD: test

NAIS_APP_NAME: klage-arkiver-journalpost

PDF_SERVICE_URL: http://localhost:8080/api/v1/genpdf/klage-dittnav-pdfgen/klage