spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/klage
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
  main:
    banner-mode: OFF

server:
  port: 7075
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true

# Local environment settings. Will be overridden in dev and prod.

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_GROUP_ID: klage-arkiver-journalpost
KAFKA_TOPIC: aapen-klager-klageOpprettet

SERVICE_USER_USERNAME: srvklage-dittnav
SERVICE_USER_PASSWORD: test

DB_HOST: localhost
DB_USERNAME: klage
DB_PASSWORD: klage

NAIS_APP_NAME: klage-arkiver-journalpost

SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088

PDL_BASE_URL: http://localhost:7000/graphql

STS_APIKEY: test
PDL_APIKEY: test