KAFKA_BOOTSTRAP_SERVERS: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw.oera.no/security-token-service
SERVICE_USER_USERNAME: srvklage-dittnav
PDF_SERVICE_URL: http://klage-dittnav-pdfgen/api/v1/genpdf/klage-dittnav-pdfgen/klage
JOARK_SERVICE_URL: https://api-gw.oera.no/dokarkiv/rest/journalpostapi/v1/journalpost
VEDLEGG_SERVICE_URL: http://klage-vedlegg-api/attachment