KAFKA_BOOTSTRAP_SERVERS: localhost:9092
SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest
PDF_SERVICE_URL: http://localhost:8080/api/v1/genpdf/klage-dittnav-pdfgen/
JOARK_SERVICE_URL: http://localhost:1234
KLAGE_FILE_API_SERVICE_URL: http://localhost:7080
KLAGE-DITTNAV-API_SERVICE_URL: http://localhost:7070
STS_APIKEY: none
JOURNALPOST_APIKEY: none
AZURE_APP_WELL_KNOWN_URL: none
AZURE_APP_CLIENT_ID: none
AZURE_APP_CLIENT_SECRET: none
KLAGE_DITTNAV_API_CLIENT_ID: none
KLAGE_FILE_API_CLIENT_ID: none