spring:
  main:
    banner-mode: OFF

server:
  port: 7075
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true

# Local environment settings. Can be overridden in dev and prod.

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_GROUP_ID: klage-arkiver-journalpost
KAFKA_TOPIC: aapen-klager-klageOpprettet

SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest

NAIS_APP_NAME: klage-arkiver-journalpost

PDF_SERVICE_URL: http://localhost:8080/api/v1/genpdf/klage-dittnav-pdfgen/klage

JOARK_SERVICE_URL: http://localhost:1234

GCS_BUCKET: klagevedlegg

SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088

STS_APIKEY: test

JOURNALPOST_APIKEY: test