spring:
  application:
    name: klage-arkiver-journalpost
  main:
    banner-mode: OFF
  codec:
    max-in-memory-size: 10MB

server:
  port: 7075
  error:
    whitelabel:
      enabled: false

navCallIdName: Nav-Callid

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    baggage:
      remote-fields:
        - ${navCallIdName}
      correlation:
        fields:
          - ${navCallIdName}

no.nav.security.jwt:
  client:
    registration:
      dokarkiv-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${DOKARKIV_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      klage-file-api-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${NAIS_CLUSTER_NAME}.${NAIS_NAMESPACE}.${KLAGE_FILE_API_APP_NAME}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      klage-dittnav-api-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${NAIS_CLUSTER_NAME}.${NAIS_NAMESPACE}.${KLAGE_DITTNAV_API_APP_NAME}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

KAFKA_TOPIC: klage.privat-klage-mottatt-v1

PDF_SERVICE_URL: http://klage-dittnav-pdfgen/api/v1/genpdf/klage-dittnav-pdfgen/
KLAGE_FILE_API_SERVICE_URL: http://klage-file-api
KLAGE_FILE_API_APP_NAME: klage-file-api
KLAGE-DITTNAV-API_SERVICE_URL: http://klage-dittnav-api
KLAGE_DITTNAV_API_APP_NAME: klage-dittnav-api

# Set to true (if for example testing in production) to ignore/stop posting journalpost to Joark.
DRY_RUN: false