spring:
  main:
    banner-mode: OFF
  codec:
    max-in-memory-size: 2MB
  sleuth:
    propagation-keys:
      - Nav-Callid
      - Nav-Consumer-Id
    log:
      slf4j:
        whitelisted-mdc-keys:
          - Nav-Callid
          - Nav-Consumer-Id

server:
  port: 7075
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

KAFKA_GROUP_ID: klage-arkiver-journalpost
KAFKA_TOPIC: aapen-klager-klageOpprettet

navCallId: Nav-Callid
navConsumerId: Nav-Consumer-Id

PDF_SERVICE_URL: http://klage-dittnav-pdfgen/api/v1/genpdf/klage-dittnav-pdfgen/klage
SERVICE_USER_USERNAME: srvklage-dittnav
VEDLEGG_SERVICE_URL: http://klage-vedlegg-api/attachment
KLAGE-DITTNAV-API_SERVICE_URL: http://klage-dittnav-api

# Set to true (if for example testing in production) to ignore/stop posting journalpost to Joark.
DRY_RUN: false