apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: klage-arkiver-journalpost
  namespace: klage
  labels:
    team: klage
spec:
  image: {{ image }}
  port: 7075
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  ingresses:
    - https://klage-arkiver-journalpost.dev-nav.no
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  secureLogs:
    enabled: true
  webproxy: true
  accessPolicy:
    outbound:
      external:
        - host: api-gw-q1.oera.no
        - host: b27apvl00045.preprod.local
        - host: b27apvl00046.preprod.local
        - host: b27apvl00047.preprod.local

  envFrom:
    - secret: srvklage-dittnav
    - secret: sts-apikey
    - secret: journalpost-apikey
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp