apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: klage-arkiver-journalpost
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "200"
spec:
  image: {{ image }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafka_pool}}
  port: 7075
  startup:
    failureThreshold: 5
    initialDelay: 10
    path: /internal/health
    periodSeconds: 10
    timeout: 3
  liveness:
    path: /internal/health
    timeout: 3
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /internal/health
    timeout: 3
    periodSeconds: 5
    failureThreshold: 3
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 20m
      memory: 1024Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  webproxy: true
  accessPolicy:
    outbound:
      rules:
        - application: klage-dittnav-pdfgen
        - application: klage-file-api
        - application: klage-dittnav-api
        - application: kabal-api
        - application: logging
          namespace: nais-system
      external:
      {{#each externalHosts as |host|}}
        - host: {{host}}
      {{/each}}
  envFrom:
    - secret: srvklage-dittnav
    - secret: sts-apikey
    - secret: journalpost-apikey
    - secret: slack-url
    - secret: slack-channel-id
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}