name: Deploy build-tag to all environments in dev-gcp

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  detect-dev-environments:
    name: Detect dev environments to deploy to
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.create-strategy-matrix.outputs.environments }}
    steps:
      - uses: actions/checkout@v4
      - id: create-strategy-matrix
        run: echo "environments=$(array=($(ls deploy/q*config.json | sed -nr 's/deploy\/(.*)\-config.json/\1/p')); printf '%s\n' "${array[@]}" | jq -R . | jq -s -c .)" >> $GITHUB_OUTPUT
      - id: print-dev-environments
        run: echo "List of dev environments to deploy to is ${{ steps.create-strategy-matrix.outputs.environments }}"

  deploy-to-dev:
    uses: navikt/klage-arkiver-journalpost/.github/workflows/deploy-to-specific-dev.yaml@multiple_environments
    needs: detect-dev-environments
    permissions:
      id-token: write
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-dev-environments.outputs.environments) }}
    with:
      image: ${{ inputs.image }}
      nav-cluster: dev-gcp
      nav-environment: ${{ matrix.environment }}
    secrets: inherit